sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      install:
      - pip install flake8
      script:
      - flake8
      - flake8 `find bin -type f | while read in ; do if file --mime-type "${in}" | grep -q python ; then echo "${in}" ; fi ; done;`
