sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      install:
      - pip install flake8
      script:
      - flake8
      - flake8 $(find bin -type f -exec file --mime-type {} \; | grep python | cut -f1 -d:)
